---
# vars file for monit-tools

url_repo_helm: https://kubernetes-charts.storage.googleapis.com
deploy_prometheus: "--set prometheusOperator.createCustomResource=false app-prometheus stable/prometheus-operator"