- name: Clean cluster Old
  command:
    kubeadm reset --force
  register: kubeadm_reset

- name: Start cluster k8s
  command:
    kubeadm init --control-plane-endpoint "k8s-haproxy01:6443" --upload-certs 
  register: kubeadm_init
  
#- remote_action: copy content={{ kubeadm_init }} dest=/tmp/file
#############
- name: Write results to logfile
  blockinfile:
    create: yes
    path: "/var/log/init.log"
    insertafter: BOF
    block: "{{ kubeadm_init.stdout }}"
    marker: "# {{ inventory_hostname }} {mark}"
#############
- name: Change file ownership, group and permissions
  file:
    path: /var/log/init.log
    owner: root
    group: root
    mode: '0775'

- name: Get Certificate Key
  shell: cat /var/log/init.log | grep discovery-token-ca-cert-hash | cut -d ' ' -f6 | sed -n '2p'
  register: token_ca_cert

- name: Get Certificate Key
  shell: cat /var/log/init.log | grep certificate-key | cut -d ' ' -f7 | sed -n '1p'
  register: certificate_key

- name: Create .kube
  file:
    path: ~/.kube
    state: directory

- name: Link file admin.conf to ~/.kube/config
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link

- name: Config pod network Weavenet
  shell: kubectl apply -f {{ default_url_weavenet }}
  register: weavenet_result

- name: Get token to add the workers in cluster
  shell: kubeadm token list | cut -d ' ' -f1  | sed -n '2p'
  register: k8s_token

- name: CA Hash
  shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  register: k8s_master_ca_hash

- name: Add o token and hash in dummy host
  add_host:
    name: "K8S_TOKEN_HOLDER"
    token: "{{ k8s_token.stdout }}"
    hash: "{{ k8s_master_ca_hash.stdout }}"
    token_ca_cert: "{{ certificate_key.stdout }}"
    certificate_key: "{{ certificate_key.stdout }}"


- name:
  debug:
    msg: "[MASTER] K8S_TOKEN_HOLDER - The token is {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"

- name:
  debug:
    msg: "[MASTER] K8S_TOKEN_HOLDER - The hash is {{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"

- name:
  debug:
    msg: "[MASTER] K8S_TOKEN_HOLDER - The token_ca_cert {{ hostvars['K8S_TOKEN_HOLDER']['token_ca_cert'] }}"

- name:
  debug:
    msg: "[MASTER] K8S_TOKEN_HOLDER - The certificate_key {{ hostvars['K8S_TOKEN_HOLDER']['certificate_key'] }}"

